services:
  app:
    container_name: liter-alura
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/liter-alura-database
      DATASOURCE_USER: alura2024
      DATASOURCE_PASSWORD: alurachallenge
    ports:
      - '8080'
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: liter-alura-database
      POSTGRES_USER: alura2024
      POSTGRES_PASSWORD: alurachallenge
    ports:
      - '5432'
  redis:
    image: redis:latest
    ports:
      - '6379'